# Istanzia Yolo

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

from yolo_v4 import YoloV4
from configs.yolo_v4 import anchor_dict
from configs.train_config import NUM_CLASSES
from utils import non_max_suppression, draw_outputs

In [2]:
yolo = YoloV4(num_classes=NUM_CLASSES)
#yolo.predict(np.zeros((1,128,128,3)))
yolo.load_weights(filepath='../checkpoints/yolo/model-best.h5')

## Standard Image Demo

In [3]:
image = cv2.imread('../checkpoints/example3.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.imshow(image)
image = np.array(image)
#wimage = tf.expand_dims(image,0)
img_tensor = np.expand_dims(image, axis=0)
img_tensor = (img_tensor/127.5)-1.0


# Prediction

In [4]:
pred = yolo.predict(img_tensor)
#print(pred)
boxes, scores, classes, nums = non_max_suppression(
    pred, anchor_dict['anchors'], anchor_dict['anchor_masks'])

print(boxes)

In [5]:

img_tensor = np.squeeze(img_tensor)
img = draw_outputs(img_tensor, boxes, scores, classes, nums)
plt.imshow(img)
plt.savefig("result")

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


BOXES
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 30, 4), dtype=float32)
OBJ
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]], shape=(1, 30), dtype=float32)
classes
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]], shape=(1, 30), dtype=float32)
nums
tf.Tensor([0], shape=(1,), dtype=int32)
